version: "3.7"
services:
  odoo:
    &odoo
    build: build/odoo
    volumes:
      - "${ODOO_DATA_VOLUME:-./data}/odoo/extra-addons:/mnt/extra-addons:rw"
      - "${ODOO_DATA_VOLUME:-./data}/odoo/:/var/lib/odoo:rw"
      - "${PWD}/odoo.conf:/etc/odoo/odoo.conf:rw"
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      USER: "${ODOO_POSTGRES_USER:-odoo}"
      PASSWORD: "${ODOO_POSTGRES_PASSWORD:-odoo}"
      HOST: db
    command: --max-cron-threads 0 --workers ${WORKERS:-4} --log-handler=:${LOG_LEVEL:-INFO}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8069" ]
      interval: "60s"
      timeout: "5s"
      retries: 3

  odoo-cron:
    <<: *odoo
    ports:
      - "8072"
    command: --max-cron-threads 1 --no-xmlrpc --log-handler=:${LOG_LEVEL:-INFO}
    #--database ${ODOO_CRON_DB:-odoo}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8072" ]
      interval: "60s"
      timeout: "5s"
      retries: 3
  db:
    image: ${POSTGRESQL_IMAGE:-postgres}:${POSTGRESQL_IMAGE_VERSION:-12-alpine}
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?POSTGRES_PASSWORD Not Set}
      ODOO_POSTGRES_USER: ${ODOO_POSTGRES_USER:-odoo}
      ODOO_POSTGRES_PASSWORD: ${ODOO_POSTGRES_PASSWORD?ODOO_POSTGRES_PASSWORD Not Set}
    volumes:
      - "${DATA_VOLUME:-./data}/postgresql:/var/lib/postgresql/data:rw"
      - "${PWD}/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "psql", "-U", "postgres", "-c", "SELECT 1;" ]
      interval: 1m
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      - "${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "${PWD}/nginx/server.crt:/etc/ssl/nginx/server.crt:rw"
      - "${PWD}/nginx/server.key:/etc/ssl/nginx/server.key:rw"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - odoo
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost" ]
      interval: "60s"
      timeout: "5s"
      retries: 3
